GET http://localhost:3000/product

###
GET http://localhost:3000/product/616bd4041410ee70dac65476

###
POST http://localhost:3000/product
Content-Type: application/json

{
    "title": "Product 2",
    "price": 2000
}

###
PATCH http://localhost:3000/product/616bd4041410ee70dac65476
Content-Type: application/json

{
    "title": "Product Update",
    "price": 3000
}

###
DELETE http://localhost:3000/product/616bd4041410ee70dac65476